#!/bin/sh

# probably the simplest pomodoro timer cli
pomo() {
    arg1=$1
    shift
    args="$*"

    min=${arg1}
    sec=$((min * 60))
    msg="${args}"

    sleep "${sec:?}" && echo "${msg:?}" && osascript -e 'display notification "'"${msg:?}"'" with title "POMO"'
}
